### PR TITLE
Solutions for gsoc_eval for AWAKE

### PR DESCRIPTION
**Pull request by linkun-1998**
The solution for the three tasks completed.
Error in getting datatypes of the datasets for some cases.
`TypeError: No NumPy equivalent for TypeBitfieldID exists`
Can be solved by additional module (PyTables)

### CODE REVIEW

**Comment by awakeExp** [comment]
Thank you, but what is your name and e-mail?

**Comment by linkun-1998** [comment]
Your welcome!
My name is Priyabrata Dash whom you replied this morning.
e-mail: priyabratadash215403@gmail.com

I was thinking of the using multilevel indexing over the previous method. As the hdf is hierarchical the multilevel indexing using the group, subgroup and dataset will add more sense.

I will create another PR with an improvement of the previous one to multilevel index.
Please you can look into it.

**Comment by linkun-1998** [comment]
I have done some changes. Please look into it.

**Comment by awakeExp** [comment]
Ok great. Please continue with the project proposal.

**Pull request closed without merging**
